---
title: "EDA Final Report"
author: "Lucy Lu (xl2602), Hanlin Wu (hw2576)"
output: 
   html_notebook:
      toc: true
      theme: united
---

## Introduction
> In this section, explain why you chose this topic, and the questions you are interested in studying. Include a brief description of how you found the data, and clear instructions on where the reader can find the data.

International travel has become so easy that anyone can just grab his/her bags and documents and starts a new journey. As one of the most tourists importing and exporting countries, the USA has always played a significant role in world’s tourism industry. Therefore, we want to study people who traveled to and from the USA by investigating the Travel and Tourism Statistical data provided by The National Travel & Tourism Office (NTTO). To be more precise, we want to answer following questions:

-	What are the most popular international travel destinations for Americans?

-	What are the main regions of people who travel to the USA?

-	What are the purposes and spending of travels to and from the USA?

-	Does the economy matter for the answers to above questions?


Data is collected from several resources,

*	`National Travel & Tourism Office (NTTO)`: On this website, we are trying to get these 4 types of data 
    + [Number of inbound overseas travelers to the U.S.](http://travel.trade.gov/outreachpages/inbound.general_information.inbound_overview.html)
    + Travel receipts (exports)
    + [Number of U.S. travelers going abroad](http://travel.trade.gov/outreachpages/outbound.general_information.outbound_overview.html) 
    + Travel payments (imports)
* [`World Bank`](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD): On this website, we are trying to get GDP per country per year, as a measurement of economy.

Although NTTO provides plenty of information we need, it is not easy to collect and combine them together. There is much unavoidable manual work to do in the collecting process because of the inconsistent formatting (data formats may vary from year to year), file types (some are pdfs) and location of these files. For example, in order to get monthly arrival information per region, we have to download each year’s excel files, and then clean, select and combine them into a final master table that is easier to manipulate with in R. 

In the end, we collect several master tables from NTTO: yearly spending per region with three categories, total monthly spending with three categories, monthly inbound visitation per country and monthly outbound visitation per country. We may use other tables as complementary tables.

GDP data from World Bank is easier to clean. Further, we will load these tables to R and use dplyr and tidyr to fit the data for our analysis. 



## Team
> List team members and a description of how each contributed to the project. (If you're working alone, briefly describe the stages of the project.)

- Lucy Lu:  finding and organizing the data, compiling visualization and stories, creating the interactive app, focusing on the import part.

- Hanlin Wu: cleaning the data, testing various visualizations, creating the interactive app, focusing on the export part.


## Analysis of Data Quality
> Provide a detailed, well-organized description of data quality, including textual description, graphs, and code.


## Executive Summary
> Provide a short nontechnical summary of the most revealing findings of your analysis with no more than 3 static graphs or one interactive graph (or link), written for a nontechnical audience. 
> The length should be approximately 2 pages (if we were using pages...) Do not show code, and take extra care to clean up your graphs, ensuring that best practices for presentation are followed.

• Note: the tips below are not intended to be a complete list of everything we've covered this semester on designing a successful graph. It's meant to help you avoid some common problems.

• Title, axis labels, tick mark labels, and legends should be comprehensible (easy to understand) and legible (easy to read / decipher).

• Tick marks should not be labeled in scientific notation or with long strings of zeros, such as 3000000000. Instead, convert to smaller numbers and change the units: 3000000000 becomes "3" and the axis label "billions of views".

• Units should be intuitive (Extreme example: an axis labeled in month/day/year format is intuitive, one labeled in seconds since January 1, 1970 is not.)

• The font size should be large enough to read clearly. The default in ggplot2 is generally too small. You can easily change it by passing the base font size to the theme, such as + theme_grey(16). (The default base font size is 11.)

• The order of items on the axes and legends is logical. (Alphabetical is often not logical.)

• Colors should be color vision deficiency friendly.

• If a legend is taking up too much space on the right, move it to the bottom.

• If categorical variable levels are long, set up the graph so the categorical variable is on the y-axis and the names are horizontal. A better option, if possible, is to shorten the names of the levels.

• Not all EDA graphs lend themselves to presentation, either because the graph form is hard to understand without practice or it's not well labeled. The labeling problem can be solved by adding text in an image editor. The downside is that it is not reproducible. If you want to go this route, Paintbrush is a free and simple bitmap image editor for the Mac: https://paintbrush.sourceforge.io/ There are many other options.

• Err on the side of simplicity. Don't, for example, overuse color when it's not necessary. Ask yourself: does color make this graph any clearer? If it doesn't, leave it out.

• Test your graphs on nontechnical friends and family and ask for feedback.

## Main Analysis
> Provide a detailed, well-organized description of your findings, including textual description, graphs, and code. Your focus should be on both the results and the process. Include, as reasonable and relevant, approaches that didn't work, challenges, the data cleaning process, etc.

• The guidelines for the Executive Summary above do NOT apply to exploratory data analysis. Your main concern is designing graphs that reveal patterns and trends.

• As noted in Hmk #4, do not use circles, that is: bubbles, pie charts, or polar coordinates.

• Use stacked bar charts sparingly. Try grouped bar charts and faceting as alternatives, and only choose stacked bar charts if they truly do a better job than the alternatives for observing patterns.


## Conclusion
> Discuss limitations and future directions, lessons learned.

A note on style:
You are encouraged to be as intellectually honest as possible. That means pointing out flaws in your work, detailing obstacles, disagreements, decision points, etc. -- the kinds of "behind-the-scene" things that are important but often left out of reports. You may use the first person ("I"/"We") or specific team members' names, as relevant.





